### ISSUE TITLE
YouTube Video Transcript

### ISSUE THREAD

**Issue by Tobe2d** [bytepull/open-webui-utilities#1]
Hi,

I cant get YouTube Video Transcript tool to work corerectly. hope you dont mind giving me some tips on how to use it.
I've isntalled it using add tool in Openwebui and in the chat box I turned on the button. but it is not working I get this answer:

`I'm not sure what the YouTube transcript for that specific video URL is, as the Tools.get_youtube_transcript() function requires a URL as an argument. Can you please provide more context or clarify which part of the video's transcript you're looking for?
`

tested the same video on https://youtubetranscript.com/ and it works, could you add some guide on how to use it please.

**Comment by Greatz08** [comment]
@Tobe2d  same issue here did you find anything related to this ?

**Comment by bytepull** [comment]
Hello there

Sorry for my late reply, I was out of town.
Basically, you can import the tool in 2 ways after going to Workspace > Tools:

1. Click **+** button, then copy-paste the code within the text area
2. Click on **Import Tools** button and then select the json file from the repository (`tools/youtube_video_transcript/tools-export.json`)

<img width="1421" alt="Screenshot 2024-11-01 at 11 33 29" src="https://github.com/user-attachments/assets/24d4deec-fa96-46ba-8e3f-c7b54c944476">

After having imported the tool, open a **new** chat and activate the tool from the button on the chat bar like the picture below:

<img width="321" alt="Screenshot 2024-11-01 at 11 40 13" src="https://github.com/user-attachments/assets/bfd13688-7404-482c-b137-7f3f1de09201">

Youtube URL shall be like this example: _https://www.youtube.com/watch?v=uOYrq7SpaoQ_

The following is a working example:

<img width="1254" alt="Screenshot 2024-11-01 at 11 44 44" src="https://github.com/user-attachments/assets/161b24a2-7574-4705-88e4-6f78282c4d12">

I only managed to have custom tools working using Openweb UI via Docker container. I experienced issues when trying to build it locally via Python.

Hope this will solve your issues.

Regards

**Comment by Tobe2d** [comment]
Thanks for the reply,

I used it exactly like you mentioned, however, 

I get this answer:

![image](https://github.com/user-attachments/assets/ba6b6dca-9699-418b-aa0a-124612781b9d)

**Comment by bytepull** [comment]
Hi

I tried with your exact script and get the following:

<img width="1259" alt="Screenshot 2024-11-01 at 20 58 47" src="https://github.com/user-attachments/assets/51bca804-a879-47b8-8766-5fa1e52a0b64">

BTW I noticed you used Fast Small LLM, I'm wondering if it could be the culprit.

Can you try again using a different LLM?
I tried again with Gemma2 and got the following:

<img width="1265" alt="Screenshot 2024-11-01 at 21 01 17" src="https://github.com/user-attachments/assets/ac40df38-ee29-45a1-b99a-abab80a8ed63">

If the issue persists, can you post some pictures of Workspace > Tools screen with the configuration?

Thanks

**Comment by Tobe2d** [comment]
Oh,,, Yes it was the LLM, now working ;-)
I just had to change it into Llama 3.1

Thank you so much for the help.
